version: '3'

services:
  web:
    container_name: server
    restart: always
    build: .
    ports:
      - "3000:7070"

    links:
      - mongo

    volumes:
       - .:/usr/src/app         # Monta todo el directorio local
       - /usr/src/app/node_modules  # Volumen separado para node_modules

    environment:
      - ENVIRONMENT=production

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27018:27017"
      
    
