###
POST http://localhost:8080/api/courses HTTP/1.1
content-type: application/json

{
    "title": "",
    "description": "This course is about python programming language"
}

###
// get all courses 
GET http://localhost:8080/api/courses HTTP/1.1

###
// get course by id
GET http://localhost:8080/api/courses/67331989d439a57ec008e1 HTTP/1.1

###
// delete course by id
DELETE http://localhost:8080/api/courses/67d32a71cbcab9059d754e92 HTTP/1.1